
backend:
  name: git-gateway
  branch: main
  identity_url: https://busns-cms-test.netlify.app/.netlify/identity
  login: true
  squash_merges: true

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

identity:
  email_verified: false

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }